language: python
python:
  - 2.6
  - 2.7
env:
  - PLONE=4.0
  - PLONE=4.1
  - PLONE=4.2
matrix:
  exclude:
    - python: 2.7
      env: PLONE=4.0
    - python: 2.7
      env: PLONE=4.1
before_install:
  - pip install http://effbot.org/downloads/Imaging-1.1.6.tar.gz
install:
  - python bootstrap.py -c test-$PLONE.cfg
  - bin/buildout -N -c test-$PLONE.cfg
script:
  - bin/test
